apiVersion: v2
name: otus-chachanagov-hm2-chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: 2

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - chachanagov-hm2-database