replicaCount: 2

image: temperror/otus-chachanagov-hm:2

service:
  type: NodePort
  port: 9000

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/otusapp/sergey-chachanagov"]

postgresql:
  enabled: true
  fullnameOverride: pg-db
  postgresqlDatabase: postgres
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  service:
    port: "5432"