apiVersion: v1
kind: Secret
metadata:
  name: chachanagov-hm2-secret
type: Opaque
data:
  database_url: {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  database_user: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  database_pass: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}
