apiVersion: v1
kind: Secret
metadata:
  name: chachanagov-hm2-secret
type: Opaque
data:
  spring_datasource_url: {{ printf "jdbc:postgresql://pg-db:%s/%s?user=%s&password=%s" .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword | b64enc }}