apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-chachanagov-hm2-chart.fullname" . }}
  labels: {{- include "otus-chachanagov-hm2-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "otus-chachanagov-hm2-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels: {{- include "otus-chachanagov-hm2-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: database_url
              valueFrom:
                secretKeyRef:
                  name: chachanagov-hm2-secret
                  key: database_url
            - name: database_user
              valueFrom:
                secretKeyRef:
                  name: chachanagov-hm2-secret
                  key: database_user
            - name: database_pass
              valueFrom:
                secretKeyRef:
                  name: chachanagov-hm2-secret
                  key: database_pass