apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-chachanagov-hm2-chart.fullname" . }}
  labels: {{- include "otus-chachanagov-hm2-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "otus-chachanagov-hm2-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels: {{- include "otus-chachanagov-hm2-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: chachanagov-hm2-secret
                  key: spring_datasource_url