apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "otus-chachanagov-hm2-chart.fullname" . }}
  labels:
    {{- include "otus-chachanagov-hm2-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "otus-chachanagov-hm2-chart.fullname" . }}
              servicePort: 8000
